# Generated by Django 2.1.2 on 2018-10-24 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('specie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Species')),
            ],
        ),
    ]
