# Generated by Django 2.1.2 on 2018-10-24 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplinigAttributes',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data')),
                ('begin', models.TimeField(auto_now=True, verbose_name='Inizio')),
                ('end', models.TimeField(auto_now=True, verbose_name='Fine')),
                ('meteo', models.CharField(choices=[('M-SER', 'Sereno'), ('M-NEB', 'Nebbia'), ('M-VAR', 'Variabile'), ('M-NUV', 'Nuvoloso'), ('M-PIO', 'Nuvoloso')], max_length=15, verbose_name='Meteo')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome')),
                ('regione', models.CharField(blank=True, max_length=15, null=True, verbose_name='Regione')),
                ('provincia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Provincia')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='STrada')),
            ],
        ),
        migrations.RemoveField(
            model_name='observations',
            name='time',
        ),
        migrations.AddField(
            model_name='observations',
            name='direction',
            field=models.CharField(blank=True, choices=[('AND', 'Andata'), ('RIT', 'Ritorno'), ('IND', 'Indeterminata')], default='Adulto', max_length=15, null=True, verbose_name='Direzione'),
        ),
        migrations.AddField(
            model_name='observations',
            name='life',
            field=models.BooleanField(default=True, verbose_name='Vivi?'),
        ),
        migrations.AddField(
            model_name='observations',
            name='n',
            field=models.IntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='observations',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('IND', 'Indeterminato')], max_length=15, null=True, verbose_name='Sesso'),
        ),
        migrations.AddField(
            model_name='observations',
            name='state',
            field=models.CharField(blank=True, choices=[('JUV', 'Giovane'), ('AD', 'Adulto')], default='Adulto', max_length=15, null=True, verbose_name='Stadio vitale'),
        ),
        migrations.AddField(
            model_name='samplinigattributes',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Site'),
        ),
        migrations.AddField(
            model_name='observations',
            name='samplingattributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.SamplinigAttributes'),
        ),
    ]
