# Generated by Django 2.1.2 on 2018-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20181024_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='direction',
            field=models.CharField(blank=True, choices=[('AND', 'Andata'), ('RIT', 'Ritorno'), ('IND', 'Indeterminata')], default='Adulto', max_length=15, null=True, verbose_name='Direzione'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('IND', 'Indeterminato')], max_length=15, null=True, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='state',
            field=models.CharField(blank=True, choices=[('JUV', 'Giovane'), ('AD', 'Adulto')], default='Adulto', max_length=15, null=True, verbose_name='Stadio vitale'),
        ),
        migrations.AlterField(
            model_name='samplinigattributes',
            name='meteo',
            field=models.CharField(choices=[('M-SER', 'Sereno'), ('M-NEB', 'Nebbia'), ('M-VAR', 'Variabile'), ('M-NUV', 'Nuvoloso'), ('M-PIO', 'Nuvoloso')], max_length=15, verbose_name='Meteo'),
        ),
        migrations.AlterField(
            model_name='site',
            name='regione',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Regione'),
        ),
    ]
