# Generated by Django 2.1.2 on 2018-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20181024_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='provincia',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='site',
            name='regione',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Regione'),
        ),
    ]
