# Generated by Django 2.1.2 on 2018-10-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20181024_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome'),
        ),
    ]
