# Generated by Django 2.1.2 on 2018-10-25 08:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20181024_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observations',
            new_name='Observation',
        ),
        migrations.RenameModel(
            old_name='SamplinigAttributes',
            new_name='SamplinigAttribute',
        ),
        migrations.RenameModel(
            old_name='Species',
            new_name='Specie',
        ),
        migrations.AlterField(
            model_name='site',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Strada'),
        ),
    ]
