# Generated by Django 2.1.2 on 2018-10-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_auto_20181025_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='n',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='observations.Specie'),
        ),
        migrations.AlterField(
            model_name='samplinigattribute',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='observations.Site'),
        ),
    ]
