# Generated by Django 2.1.2 on 2018-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_auto_20181025_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SamplinigAttribute',
            new_name='Session',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='samplingattributes',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='observation',
            name='direction',
            field=models.CharField(blank=True, choices=[('RIP', 'Riproduzione'), ('SVE', 'Svernamento'), ('IND', 'Indeterminata')], default='Adulto', max_length=15, null=True, verbose_name='Direzione'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='n',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero individui'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, help_text='Nome identificativo del sito che lo renda riconoscibile da chiunque', max_length=300, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='iucn',
            field=models.URLField(blank=True, help_text='URL della paigna IUCN della specie, se in lista rossa', max_length=300, null=True, verbose_name='IUCN'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='picture',
            field=models.ImageField(blank=True, help_text='Una immagine rappresentativa della specie', null=True, upload_to='species/%Y-%m-%d/', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='vernacular_en',
            field=models.CharField(blank=True, help_text='Nome comune inglese', max_length=100, null=True, verbose_name='Nome inglese'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='vernacular_it',
            field=models.CharField(blank=True, help_text='Nome comune italiano', max_length=100, null=True, verbose_name='Nome italiano'),
        ),
    ]
