# Generated by Django 2.1.2 on 2018-10-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_auto_20181025_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specie',
            old_name='picture',
            new_name='image',
        ),
    ]
