# Generated by Django 2.1.2 on 2018-10-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_auto_20181027_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Una immagine rappresentativa della specie', null=True, upload_to='species/%Y-%m-%d/', verbose_name='Immagine')),
            ],
        ),
        migrations.RemoveField(
            model_name='specie',
            name='image',
        ),
        migrations.AddField(
            model_name='specieimage',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='observations.Specie'),
        ),
    ]
