# Generated by Django 2.1.2 on 2018-10-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_auto_20181027_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='iucn',
            field=models.URLField(blank=True, help_text='URL della pagina IUCN della specie, se in lista rossa', max_length=300, null=True, verbose_name='IUCN'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to='species/%Y-%m-%d/', verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specieimages', to='observations.Specie'),
        ),
    ]
