# Generated by Django 2.1.2 on 2018-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_auto_20181027_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='specieimage',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Autore'),
        ),
    ]
