# Generated by Django 2.1.2 on 2018-10-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_specieimage_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specieimage',
            options={'verbose_name': 'Immagine della specie', 'verbose_name_plural': 'Immagini di specie'},
        ),
    ]
