# Generated by Django 2.1.2 on 2018-10-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_auto_20181027_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name': 'Detaglio specie', 'verbose_name_plural': 'Dettagli specie'},
        ),
        migrations.AlterModelOptions(
            name='specieimage',
            options={'verbose_name': 'Immagine della specie', 'verbose_name_plural': 'Immagini della specie'},
        ),
    ]
