# Generated by Django 2.1.2 on 2018-10-28 10:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_auto_20181027_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='descrizione',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descrizione'),
        ),
    ]
