# Generated by Django 2.1.2 on 2018-10-28 14:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0018_siteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative del sito', null=True, upload_to='sites/%Y-%m-%d/', verbose_name='Immagine'),
        ),
    ]
