# Generated by Django 2.1.2 on 2018-10-28 14:59

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0019_auto_20181028_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to='species/%Y-%m-%d/', verbose_name='Immagine'),
        ),
    ]
