# Generated by Django 2.1.2 on 2018-10-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0020_auto_20181028_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Sito di salvataggio', 'verbose_name_plural': 'Siti di salvataggio'},
        ),
    ]
