# Generated by Django 2.1.2 on 2018-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0021_auto_20181028_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Sessione', 'verbose_name_plural': 'Sessioni'},
        ),
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name': 'Specie', 'verbose_name_plural': 'Specie'},
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
    ]
