# Generated by Django 2.1.2 on 2018-10-31 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0023_auto_20181029_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 13, 40, 53, 240553), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 31, 13, 40, 53, 240525), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 13, 40, 53, 240577), verbose_name='Fine'),
        ),
    ]
