# Generated by Django 2.1.2 on 2018-10-31 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0025_auto_20181031_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 13, 45, 6, 768972), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 31, 13, 45, 6, 768944), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 13, 45, 6, 768993), verbose_name='Fine'),
        ),
    ]
