# Generated by Django 2.1.2 on 2018-10-31 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0028_auto_20181031_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 15, 7, 5, 374590, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 31, 15, 7, 5, 374559, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 10, 31, 15, 7, 5, 374615, tzinfo=utc), verbose_name='Fine'),
        ),
    ]
