# Generated by Django 2.1.2 on 2018-11-01 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0029_auto_20181031_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 11, 1, 18, 55, 15, 411040, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 18, 55, 15, 411007, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 11, 1, 18, 55, 15, 411066, tzinfo=utc), verbose_name='Fine'),
        ),
        migrations.AlterField(
            model_name='session',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Gradi centigradi', null=True, verbose_name='Temperatura'),
        ),
    ]
