# Generated by Django 2.1.3 on 2018-12-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0038_auto_20181128_1708'),
        ('observations', '0034_auto_20181128_1634'),
    ]

    operations = [
    ]
