# Generated by Django 2.1.2 on 2018-12-10 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0039_merge_20181210_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Specie'),
        ),
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 11, 14, 9, 147603, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 11, 14, 9, 147572, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 11, 14, 9, 147628, tzinfo=utc), verbose_name='Fine'),
        ),
    ]
