# Generated by Django 2.1.2 on 2018-12-10 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0040_auto_20181210_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='Attivo?'),
        ),
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 14, 45, 20, 457921, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 14, 45, 20, 457891, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 14, 45, 20, 457946, tzinfo=utc), verbose_name='Fine'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
