# Generated by Django 2.1.4 on 2018-12-10 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_auto_20181210_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 14, 8, 50, 336275, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 14, 8, 50, 336243, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 14, 8, 50, 336301, tzinfo=utc), verbose_name='Fine'),
        ),
        migrations.AlterField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='specie',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
