# Generated by Django 2.1.2 on 2018-12-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_auto_20181210_1545'),
        ('observations', '0042_auto_20181210_1508'),
    ]

    operations = [
    ]
