# Generated by Django 2.1.2 on 2018-12-10 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0043_merge_20181210_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 16, 26, 9, 820319, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 10, 16, 26, 9, 820288, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 10, 16, 26, 9, 820346, tzinfo=utc), verbose_name='Fine'),
        ),
    ]
