# Generated by Django 2.1.2 on 2018-12-19 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0044_auto_20181210_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='wiki',
            field=models.URLField(blank=True, help_text='URL della pagina Wikipedia della specie', max_length=300, null=True, verbose_name='WIki'),
        ),
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 19, 20, 33, 11, 491940, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 19, 20, 33, 11, 491906, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 19, 20, 33, 11, 491967, tzinfo=utc), verbose_name='Fine'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='iucn',
            field=models.URLField(blank=True, help_text='URL della pagina IUCN della specie', max_length=300, null=True, verbose_name='IUCN'),
        ),
    ]
