# Generated by Django 2.1.2 on 2018-12-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0045_auto_20181219_2133'),
        ('observations', '0045_auto_20181219_2144'),
    ]

    operations = [
    ]
