# Generated by Django 2.1.2 on 2018-12-23 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0046_merge_20181223_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='volontari',
            field=models.CharField(blank=True, max_length=2046, null=True, verbose_name='Volontari'),
        ),
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 23, 9, 6, 0, 166994, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 23, 9, 6, 0, 166964, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 23, 9, 6, 0, 167020, tzinfo=utc), verbose_name='Fine'),
        ),
        migrations.AlterField(
            model_name='session',
            name='meteo',
            field=models.CharField(choices=[('M-SER', 'Sereno'), ('M-NEB', 'Nebbia'), ('M-VAR', 'Variabile'), ('M-NUV', 'Nuvoloso'), ('M-PRE', 'Precipitazione')], max_length=15, verbose_name='Meteo'),
        ),
    ]
