# Generated by Django 2.1.2 on 2018-12-23 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0047_auto_20181223_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'ordering': ('specie',), 'verbose_name': 'Specie', 'verbose_name_plural': 'Specie'},
        ),
        migrations.AlterField(
            model_name='session',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2018, 12, 23, 9, 19, 57, 735327, tzinfo=utc), verbose_name='Inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 23, 9, 19, 57, 735296, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(default=datetime.datetime(2018, 12, 23, 9, 19, 57, 735351, tzinfo=utc), verbose_name='Fine'),
        ),
    ]
