# Generated by Django 2.1.2 on 2018-12-27 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0049_auto_20181223_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Nome')),
                ('regione', models.TextField(blank=True, null=True, verbose_name='Regione')),
                ('provincia', models.TextField(blank=True, null=True, verbose_name='Provincia')),
                ('descrizione', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descrizione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo?')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Strada')),
                ('volontari', models.TextField(blank=True, null=True, verbose_name='Volontari')),
            ],
            options={
                'verbose_name': 'Sito di salvataggio',
                'verbose_name_plural': 'Siti di salvataggio',
                'db_table': 'sitewithvolunteers',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='observation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='observations.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='observations.Site', verbose_name='Sito di salvataggio'),
        ),
    ]
