# Generated by Django 2.1.2 on 2018-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0050_auto_20181227_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='sitename', max_length=50, null=True, verbose_name='Nome sito')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Anno')),
                ('specie', models.TextField(blank=True, max_length=40, null=True, verbose_name='Specie')),
                ('sex', models.TextField(blank=True, max_length=10, null=True, verbose_name='Sesso')),
                ('life', models.BooleanField(default=True, verbose_name='Vivo?')),
                ('n', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Riassunti per sito',
                'verbose_name_plural': 'Riassunti per sito',
                'db_table': 'sitesummary',
                'managed': False,
            },
        ),
    ]
