# Generated by Django 2.1.2 on 2020-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0052_auto_20190321_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaVolontari',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('cognome', models.TextField(verbose_name='Cognome')),
                ('regione', models.TextField(verbose_name='Regione di interesse')),
                ('provincia', models.TextField(verbose_name='Provincia di interesse')),
            ],
            options={
                'verbose_name': 'Volontario',
                'verbose_name_plural': 'Volontari',
                'ordering': ('nome', 'cognome'),
            },
        ),
        migrations.AddField(
            model_name='session',
            name='volontari_key',
            field=models.ManyToManyField(blank=True, related_name='Volontari', to='observations.AnagraficaVolontari'),
        ),
    ]
