# Generated by Django 2.1.2 on 2020-02-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0054_auto_20200212_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficavolontari',
            name='cognome',
            field=models.CharField(max_length=256, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='anagraficavolontari',
            name='nome',
            field=models.CharField(max_length=256, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='anagraficavolontari',
            name='provincia',
            field=models.CharField(max_length=256, verbose_name='Provincia di interesse'),
        ),
        migrations.AlterField(
            model_name='anagraficavolontari',
            name='regione',
            field=models.CharField(max_length=256, verbose_name='Regione di interesse'),
        ),
    ]
