# Generated by Django 2.1.2 on 2020-02-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0055_auto_20200212_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anagraficavolontari',
            old_name='id',
            new_name='anagrafica_volontari_id',
        ),
    ]
