# Generated by Django 2.1.2 on 2020-02-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0056_auto_20200212_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagraficavolontari',
            name='anagrafica_volontari_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anagraficavolontari',
            name='session',
            field=models.ManyToManyField(blank=True, null=True, to='observations.Session', verbose_name='Sessioni alle quali il volontario ha partecipato'),
        ),
    ]
