# Generated by Django 2.1.2 on 2020-02-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0057_auto_20200212_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficavolontari',
            name='anagrafica_volontari_id',
        ),
        migrations.AddField(
            model_name='anagraficavolontari',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
