# Generated by Django 2.1.2 on 2020-02-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0059_auto_20200212_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagraficavolontari',
            name='session',
        ),
        migrations.DeleteModel(
            name='AnagraficaVolontari',
        ),
    ]
