# Generated by Django 2.1.2 on 2020-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0060_auto_20200213_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='volontari',
        ),
        migrations.AddField(
            model_name='session',
            name='volontari_unregistered',
            field=models.CharField(blank=True, help_text='Nome e cognome dei volontari partecipanti alla serata (iniziali maiuscole), separati da virgola', max_length=2046, null=True, verbose_name='Volontari non registrati'),
        ),
    ]
