# Generated by Django 2.1.2 on 2020-02-13 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0062_auto_20200213_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_added_related', to=settings.AUTH_USER_MODEL, verbose_name='Aggiunto da'),
        ),
        migrations.AddField(
            model_name='observation',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_added_related', to=settings.AUTH_USER_MODEL, verbose_name='Aggiunto da'),
        ),
        migrations.AddField(
            model_name='session',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_added_related', to=settings.AUTH_USER_MODEL, verbose_name='Aggiunto da'),
        ),
        migrations.AddField(
            model_name='site',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da'),
        ),
    ]
