# Generated by Django 2.1.2 on 2020-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0063_auto_20200213_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='temperature_interpolated',
            field=models.FloatField(blank=True, help_text='La temperatura media in gradi centigradi segnata dalla centrale meteo più vicina durante il periodo di monitoraggio', null=True, verbose_name='Temperatura (da meteo)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='temperature',
            field=models.FloatField(blank=True, help_text='La temperatura media in gradi centigradi registrata durante il monitoraggio, direttamente sul sito', null=True, verbose_name='Temperatura (locale)'),
        ),
    ]
