# Generated by Django 2.1.2 on 2020-02-13 18:46

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0064_auto_20200213_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='flyer',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Flyer di avviso attraversamento anfibi', null=True, upload_to=observations.models.flyer_upload_function, verbose_name='Flyer avviso'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='wiki',
            field=models.URLField(blank=True, help_text='URL della pagina Wikipedia della specie', max_length=300, null=True, verbose_name='Wiki'),
        ),
    ]
