# Generated by Django 2.1.2 on 2020-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0065_auto_20200213_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='direction',
            field=models.CharField(blank=True, choices=[('AND', 'Andata'), ('RIT', 'Ritorno'), ('IND', 'Indeterminata')], default='Adulto', max_length=15, null=True, verbose_name='Direzione'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='state',
            field=models.CharField(blank=True, choices=[('NEO', 'Neometamorfosato'), ('JUV', 'Giovane'), ('AD', 'Adulto')], default='Adulto', max_length=15, null=True, verbose_name='Stadio vitale'),
        ),
    ]
