# Generated by Django 2.1.2 on 2020-02-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0066_auto_20200219_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('date',), 'verbose_name': 'Uscita di salvataggio', 'verbose_name_plural': 'Uscite di salvataggio'},
        ),
    ]
