# Generated by Django 2.1.2 on 2020-02-23 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0067_auto_20200219_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationDetail',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alive_female_andata', models.PositiveIntegerField(default=0, verbose_name='Numero femmine vive in andata')),
                ('alive_male_andata', models.PositiveIntegerField(default=0, verbose_name='Numero maschi vivi in andata')),
                ('alive_female_ritorno', models.PositiveIntegerField(default=0, verbose_name='Numero femmine vive in ritorno')),
                ('alive_male_ritorno', models.PositiveIntegerField(default=0, verbose_name='Numero maschi vivi in ritorno')),
                ('dead_female', models.PositiveIntegerField(default=0, verbose_name='Numero femmine morte')),
                ('dead_male', models.PositiveIntegerField(default=0, verbose_name='Numero maschi morti')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observationdetail_added_related', to=settings.AUTH_USER_MODEL, verbose_name='Aggiunto da')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observationdetail_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail_session', to='observations.Session')),
                ('specie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail_specie', to='observations.Specie')),
            ],
            options={
                'verbose_name': 'Osservazione dettagliata',
                'verbose_name_plural': 'Osservazioni dettagliate',
            },
        ),
    ]
