# Generated by Django 2.1.2 on 2020-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0068_observationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdetail',
            name='dead_indet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero indeterminati morti'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='indet_andata',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero indeterminati vivi in ritoro'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='alive_female_andata',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero femmine vive in andata'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='alive_female_ritorno',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero femmine vive in ritorno'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='alive_male_andata',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero maschi vivi in andata'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='alive_male_ritorno',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero maschi vivi in ritorno'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='dead_female',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero femmine morte'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='dead_male',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero maschi morti'),
        ),
    ]
