# Generated by Django 2.1.2 on 2020-02-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0069_auto_20200223_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationdetail',
            options={'verbose_name': 'Dettaglio per una specie', 'verbose_name_plural': 'Dettagli per le specie'},
        ),
    ]
