# Generated by Django 2.1.2 on 2020-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0071_auto_20200223_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='comune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comune'),
        ),
    ]
