# Generated by Django 2.1.2 on 2020-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0072_site_comune'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='type',
            field=models.CharField(choices=[('Inquadramento', 'Inquadramento'), ('Sito riproduttivo', 'Sito riproduttivo'), ('Sito di svernamento', 'Sito di svernamento'), ('Barriere', 'Barriere'), ('Volontari', 'Volontari'), ('Condizioni', 'Condizioni'), ('Mortalità', 'Mortalità'), ('Altro', 'Altro')], default='Altro', max_length=300, verbose_name='Tipo immagine'),
            preserve_default=False,
        ),
    ]
