# Generated by Django 2.2 on 2020-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0073_siteimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='meteo',
            field=models.CharField(choices=[('M-NUV', 'Nuvoloso'), ('M-PIO', 'Pioggia'), ('M-VAR', 'Variabile'), ('M-SER', 'Sereno'), ('M-NEBPIO', 'Pioggerella/Nebbia'), ('M-NEV', 'Neve')], max_length=15, verbose_name='Meteo'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, help_text='Nome identificativo del sito. Deve essere studiato in modo da poter essere riconosciuto da chiunque', max_length=300, null=True, verbose_name='Nome'),
        ),
    ]
