# Generated by Django 2.2 on 2020-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0074_auto_20200225_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-date',), 'verbose_name': 'Uscita di salvataggio', 'verbose_name_plural': 'Uscite di salvataggio'},
        ),
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='session',
            name='volontari_unregistered',
            field=models.CharField(help_text='Nome e cognome dei volontari partecipanti alla serata (iniziali maiuscole), separati da virgola', max_length=2046, null=True, verbose_name='Volontari non registrati'),
        ),
    ]
