# Generated by Django 2.2 on 2020-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0075_auto_20200225_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
