# Generated by Django 2.2 on 2020-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0076_auto_20200225_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='volontari_unregistered',
            field=models.CharField(blank=True, help_text='Nome e cognome dei volontari partecipanti alla serata (iniziali maiuscole), separati da virgola', max_length=2046, null=True, verbose_name='Volontari non registrati'),
        ),
    ]
