# Generated by Django 2.2 on 2020-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0078_auto_20200225_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationdetail',
            old_name='indet_andata',
            new_name='alive_indet_andata',
        ),
        migrations.RenameField(
            model_name='observationdetail',
            old_name='indet_ritorno',
            new_name='alive_indet_ritorno',
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='alive_female_indet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero femmine in direzione indeterminata'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='alive_indet_indet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero indeterminati vivi in direzione indeterminata'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='alive_male_indet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero maschi in direzione indeterminata'),
        ),
    ]
