# Generated by Django 2.2 on 2020-02-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0079_auto_20200225_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdetail',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail_session', to='observations.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail_specie', to='observations.Specie'),
            preserve_default=False,
        ),
    ]
