# Generated by Django 2.2 on 2020-02-28 18:20

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0081_journalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='Giornale', help_text='Immagine del giornale', upload_to='journals/%Y-%m-%d/', verbose_name='Immagine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalimage',
            name='journal',
            field=models.CharField(default='Giornale', max_length=300, verbose_name='Giornale'),
            preserve_default=False,
        ),
    ]
