# Generated by Django 2.2 on 2020-02-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0082_auto_20200228_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalimage',
            name='link',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name="Link all'articolo online"),
        ),
    ]
