# Generated by Django 2.2 on 2020-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0083_journalimage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di pubblicazione'),
        ),
    ]
