# Generated by Django 2.2 on 2020-02-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0084_auto_20200228_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalimages', to='observations.Site', verbose_name='Sito di salvataggio'),
        ),
    ]
