# Generated by Django 2.2 on 2020-02-29 09:24

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0085_auto_20200228_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', sorl.thumbnail.fields.ImageField(blank=True, help_text='Documento utile per il sito', null=True, upload_to='sites/documents/', verbose_name='Documento')),
                ('doctype', models.CharField(choices=[('Riassunto attività', 'Riassunto attività'), ('Identificazione specie', 'Identificazione specie'), ('Report', 'Report'), ('Altro', 'Altro')], max_length=300, verbose_name='Tipo documento')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data di produzione del documento')),
                ('author', models.CharField(blank=True, max_length=300, null=True, verbose_name='Autore')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitedocs', to='observations.Site')),
            ],
            options={
                'verbose_name': 'Documento del sito',
                'verbose_name_plural': 'Documenti del sito',
            },
        ),
    ]
