# Generated by Django 2.2 on 2020-02-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0086_sitedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedoc',
            name='title',
            field=models.CharField(
                default='Documento', max_length=1200, verbose_name='Titolo documento'),
            preserve_default=False,
        ),
    ]
