# Generated by Django 2.2 on 2020-02-29 09:32

from django.db import migrations
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0087_sitedoc_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedoc',
            name='doc',
            field=sorl.thumbnail.fields.ImageField(default='', help_text='Documento utile per il sito', upload_to=observations.models.doc_upload_function, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative del sito', null=True, upload_to=observations.models.image_upload_function, verbose_name='Immagine'),
        ),
    ]
