# Generated by Django 2.2 on 2020-02-29 11:20

from django.db import migrations, models
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0088_auto_20200229_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedoc',
            name='doc',
            field=models.FileField(help_text='Documento utile per il sito', upload_to=observations.models.doc_upload_function, verbose_name='Documento'),
        ),
    ]
