# Generated by Django 2.2 on 2020-02-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0090_auto_20200229_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciedoc',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciedocs', to='observations.Specie'),
        ),
    ]
