# Generated by Django 2.2 on 2020-02-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0091_auto_20200229_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observationdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.ObservationDetail', verbose_name='Osservazioni non normalizzate'),
        ),
    ]
