# Generated by Django 2.2 on 2020-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0092_observation_observationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='vento',
            field=models.CharField(choices=[('V-NO', 'Assente'), ('V-LOW', 'Scarso'), ('V-MED', 'Medio'), ('V-HIG', 'Intenso')], default='V-NO', max_length=15, verbose_name='Vento'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='direction',
            field=models.CharField(blank=True, choices=[('AND', 'Andata'), ('RIT', 'Ritorno'), ('IND', 'Indeterminata')], max_length=15, null=True, verbose_name='Direzione'),
        ),
        migrations.AlterField(
            model_name='session',
            name='meteo',
            field=models.CharField(choices=[('M-NUV', 'Nuvoloso'), ('M-PIO', 'Pioggia'), ('M-VAR', 'Variabile'), ('M-SER', 'Sereno'), ('M-NEBPIO', 'Pioggerella/Nebbia'), ('M-NEV', 'Neve')], default='M-SER', max_length=15, verbose_name='Meteo'),
        ),
    ]
