# Generated by Django 2.2 on 2020-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0093_auto_20200311_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='meteo',
            field=models.CharField(blank=True, choices=[('M-NUV', 'Nuvoloso'), ('M-PIO', 'Pioggia'), ('M-VAR', 'Variabile'), ('M-SER', 'Sereno'), ('M-NEBPIO', 'Pioggerella/Nebbia'), ('M-NEV', 'Neve')], max_length=15, null=True, verbose_name='Meteo'),
        ),
        migrations.AlterField(
            model_name='session',
            name='vento',
            field=models.CharField(blank=True, choices=[('V-NO', 'Assente'), ('V-LOW', 'Scarso'), ('V-MED', 'Medio'), ('V-HIG', 'Intenso')], max_length=15, null=True, verbose_name='Vento'),
        ),
    ]
