# Generated by Django 2.2 on 2020-03-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0094_auto_20200311_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observationdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail', to='observations.ObservationDetail', verbose_name='Osservazioni non normalizzate'),
        ),
    ]
