# Generated by Django 2.2 on 2020-03-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0095_auto_20200323_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': False, 'verbose_name': 'Osservazione', 'verbose_name_plural': 'Osservazioni'},
        ),
    ]
