# Generated by Django 2.2 on 2021-02-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0096_auto_20200323_2317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='observation',
            table='observations_exploded',
        ),
    ]
