# Generated by Django 2.2 on 2021-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0097_auto_20210207_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciedoc',
            name='doctype',
            field=models.CharField(choices=[('Identificazione specie', 'Identificazione specie'), ('Disambiguazione specie', 'Disambiguazione specie'), ('Altro', 'Altro')], max_length=300, verbose_name='Tipo documento'),
        ),
    ]
