# Generated by Django 2.2 on 2021-02-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0098_auto_20210207_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedoc',
            options={'managed': True, 'verbose_name': 'Documento del sito', 'verbose_name_plural': 'Documenti del sito'},
        ),
    ]
