# Generated by Django 2.2 on 2021-02-07 14:39

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0099_auto_20210207_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedoc',
            options={'verbose_name': 'Documento del sito di salvataggio', 'verbose_name_plural': 'Documenti associati ai siti di salvataggio'},
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='doc',
            field=models.FileField(help_text='Documento utile per la specie', upload_to=observations.models.speciedoc_upload_function, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='doctype',
            field=models.CharField(choices=[('Report', 'Report'), ('Descrizione', 'Descrizione'), ('Altro', 'Altro')], max_length=300, verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciedocs', to='observations.Site'),
        ),
    ]
