# Generated by Django 2.2 on 2021-02-07 14:40

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0100_auto_20210207_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedoc',
            options={'managed': True, 'verbose_name': 'Documento del sito', 'verbose_name_plural': 'Documenti del sito'},
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='doc',
            field=models.FileField(help_text='Documento utile per il sito', upload_to=observations.models.doc_upload_function, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='doctype',
            field=models.CharField(choices=[('Riassunto attività', 'Riassunto attività'), ('Identificazione specie', 'Identificazione specie'), ('Report', 'Report'), ('Altro', 'Altro')], max_length=300, verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitedocs', to='observations.Site'),
        ),
    ]
