# Generated by Django 2.2 on 2021-02-07 14:45

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0102_auto_20210207_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedoc',
            name='doc',
            field=models.FileField(help_text='Documento utile per il sito', upload_to=observations.models.sitedoc_upload_function, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitedocs', to='observations.Site'),
        ),
    ]
