# Generated by Django 2.2 on 2021-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0103_auto_20210207_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='specie_connected',
            field=models.ManyToManyField(blank=True, related_name='specieconnected', to='observations.Specie', verbose_name='Specie con la quale può essere confusa'),
        ),
        migrations.AlterField(
            model_name='session',
            name='volontari',
            field=models.ManyToManyField(blank=True, to='profiles.Profile', verbose_name='Volontari registrati'),
        ),
    ]
