# Generated by Django 2.2 on 2021-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0104_auto_20210207_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='specie_connected',
            field=models.ManyToManyField(blank=True, related_name='specieconnected', to='observations.Specie', verbose_name='Specie con le quali può essere confusa'),
        ),
    ]
