# Generated by Django 2.2 on 2021-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0105_auto_20210208_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdetail',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='specie',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
