# Generated by Django 2.2 on 2021-02-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0106_auto_20210209_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': False, 'ordering': ['-session__date', 'specie__name', 'state', 'direction', 'life', 'n'], 'verbose_name': 'Osservazione', 'verbose_name_plural': 'Osservazioni'},
        ),
        migrations.AlterModelOptions(
            name='sitesummary',
            options={'managed': False, 'ordering': ['-year', 'specie', 'sex', 'direction', 'alive', 'n'], 'verbose_name': 'Riassunti per sito', 'verbose_name_plural': 'Riassunti per i siti'},
        ),
    ]
