# Generated by Django 2.2 on 2021-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0107_auto_20210228_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdetail',
            name='giovani',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero giovani'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='neometamorfosati',
            field=models.CharField(blank=True, choices=[('pochi', '<10'), ('medi', '10-100'), ('molti', '100-1000'), ('moltissimi', '>1000')], max_length=128, null=True, verbose_name='Stima neometamorfosati'),
        ),
    ]
