# Generated by Django 2.2 on 2021-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0108_auto_20210319_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='meteoblue_widget',
            field=models.TextField(blank=True, null=True, verbose_name='Widget MeteoBlue'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='neometamorfosati',
            field=models.CharField(blank=True, choices=[('pochi', '<10'), ('medi', '10-100'), ('molti', '100-1000'), ('moltissimi', '>1000')], max_length=128, null=True, verbose_name='Stima numero neometamorfosati'),
        ),
    ]
