# Generated by Django 2.2 on 2021-05-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0109_auto_20210411_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(verbose_name='Data di inizio dei salvataggi')),
                ('date_end', models.DateField(verbose_name='Data di fine dei salvataggi')),
                ('date_barriers_begin', models.DateField(verbose_name='Data di posa delle barriere, se presenti')),
                ('date_barriers_end', models.DateField(verbose_name='Data di rimozione delle barriere, se presenti')),
                ('year', models.IntegerField(default=2021, verbose_name='Anno')),
                ('andamento', models.TextField(blank=True, null=True, verbose_name='Andamento generale della migrazione')),
                ('note_sito', models.TextField(blank=True, null=True, verbose_name='Note relative alla gestione del sito di salvataggio')),
                ('note_traffico', models.TextField(blank=True, null=True, verbose_name='Note relative al traffico veicolare')),
                ('note_fauna', models.TextField(blank=True, null=True, verbose_name='Note relative alle particolarità faunistiche')),
                ('problematiche', models.TextField(blank=True, null=True, verbose_name='Problematiche generali')),
                ('note_altro', models.TextField(blank=True, null=True, verbose_name='Altre segnalazioni')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Site', verbose_name='Sito di salvataggio')),
            ],
            options={
                'verbose_name': 'Report annuale',
                'verbose_name_plural': 'Report annuali',
            },
        ),
    ]
