# Generated by Django 2.2 on 2021-05-11 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0110_yearlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearlyreport_added_related', to=settings.AUTH_USER_MODEL, verbose_name='Aggiunto da'),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearlyreport_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da'),
        ),
    ]
