# Generated by Django 2.2 on 2021-05-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0111_auto_20210511_0755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yearlyreport',
            unique_together={('site', 'year')},
        ),
    ]
