# Generated by Django 2.2 on 2021-05-22 06:42

from django.db import migrations, models
import django.db.models.deletion
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0114_yearlyreport_note_riservate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyreport',
            name='note_riservate',
            field=models.TextField(blank=True, help_text='Queste note sono disponibili ai soli referenti campo utile per inserire informazioni sensibili', null=True, verbose_name='Note riservate'),
        ),
        migrations.CreateModel(
            name='YearlyReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, help_text="Immagini rappresentative dell'anno di monitoraggio", null=True, upload_to=observations.models.yearlyreportimage_upload_function, verbose_name='Immagine')),
                ('author', models.CharField(blank=True, max_length=300, null=True, verbose_name='Autore')),
                ('yearly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlyreportimages', to='observations.YearlyReport')),
            ],
            options={
                'verbose_name': 'Immagine della annata di monitoraggio',
                'verbose_name_plural': 'Immagini della annata di monitoraggio',
            },
        ),
    ]
