# Generated by Django 2.2 on 2021-05-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0115_auto_20210522_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyreport',
            name='n_uscite',
            field=models.IntegerField(default=1, editable=False, verbose_name='Numero di uscite'),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='n_volontari',
            field=models.IntegerField(default=1, editable=False, verbose_name='Numero di volontari'),
        ),
    ]
