# Generated by Django 2.2 on 2021-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0117_yearlyreportimage_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyreportimage',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Autorice/autore'),
        ),
    ]
