# Generated by Django 2.2 on 2021-05-27 12:01

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0119_auto_20210527_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationdetail',
            name='neometamorfosati',
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='neometamorfosati_morti_stima',
            field=models.CharField(blank=True, choices=[('pochi', '<10'), ('medi', '10-100'), ('molti', '100-1000'), ('moltissimi', '>1000')], max_length=128, null=True, verbose_name='Stima numero neometamorfosati morti'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='neometamorfosati_vivi_stima',
            field=models.CharField(blank=True, choices=[('pochi', '<10'), ('medi', '10-100'), ('molti', '100-1000'), ('moltissimi', '>1000')], max_length=128, null=True, verbose_name='Stima numero neometamorfosati vivi'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
