# Generated by Django 2.2 on 2021-06-06 14:28

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0123_auto_20210527_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdetail',
            name='neometamorfosati_morti',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero approssimativo neometamorfosati morti'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='neometamorfosati_vivi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero approssimativo neometamorfosati vivi'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
