# Generated by Django 2.2 on 2022-02-19 09:57

from django.db import migrations
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0132_auto_20220219_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='comune_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='provincia_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='regione_id',
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
