# Generated by Django 2.2 on 2022-02-19 09:58

from django.db import migrations, models
import django.db.models.deletion
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20220219_1055'),
        ('observations', '0133_auto_20220219_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='comune_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Comuni'),
        ),
        migrations.AddField(
            model_name='site',
            name='provincia_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Province'),
        ),
        migrations.AddField(
            model_name='site',
            name='regione_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Regioni'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
