# Generated by Django 2.2 on 2022-03-16 06:35

from django.db import migrations, models
import django.utils.timezone
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0140_auto_20220316_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_begin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_begin',
            field=models.TimeField(verbose_name='Ora di inizio'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(verbose_name='Ora di fine'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
