# Generated by Django 2.2 on 2022-03-16 06:44

from django.db import migrations, models
import django.utils.timezone
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0141_auto_20220316_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-date',), 'verbose_name': 'Uscita di salvataggio', 'verbose_name_plural': 'Uscite di salvataggio'},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='time_end',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time_begin',
        ),
        migrations.AddField(
            model_name='session',
            name='begin',
            field=models.TimeField(default='00:00:00', verbose_name="Ora d'inizio"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='session',
            name='ended_next_day',
            field=models.BooleanField(default=False, verbose_name='Terminato il giorno dopo?'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
