# Generated by Django 2.2 on 2022-04-21 06:14

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0148_auto_20220326_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-date', '-begin', 'site'), 'verbose_name': 'Uscita di salvataggio', 'verbose_name_plural': 'Uscite di salvataggio'},
        ),
        migrations.AlterField(
            model_name='session',
            name='volontari',
            field=models.ManyToManyField(blank=True, help_text='Iniziare a digitare un nome, quindi ->>>CLICCARE<<<- sul nome che si desidera aggiungere', to='profiles.Profile', verbose_name='Volontari registrati (CON PROFILO SU SAVE THE PRINCE)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='volontari_unregistered',
            field=models.CharField(blank=True, help_text="Iniziali maiuscole, separare con virgola un volontario dall'altro", max_length=2046, null=True, verbose_name='Volontari non registrati (SENZA PROFILO SU SAVE THE PRINCE)'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
