# Generated by Django 2.2 on 2022-04-29 07:01

from django.db import migrations, models
import django.db.models.deletion
import observations.models
import sorl.thumbnail.fields
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0150_auto_20220426_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
        migrations.CreateModel(
            name='SessionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini dellaa sessione', null=True, upload_to='sessions/%Y-%m-%d/', verbose_name='Immagine')),
                ('descr', utils.models.ShortTextField(blank=True, null=True, verbose_name='Descrizione eventuale')),
                ('author', models.CharField(blank=True, max_length=300, null=True, verbose_name='Autorice/autore')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionimages', to='observations.Session')),
            ],
            options={
                'verbose_name': 'Immagine della sessione',
                'verbose_name_plural': 'Immagini della sessione',
            },
        ),
    ]
