# Generated by Django 4.1 on 2023-02-22 12:12

from django.db import migrations, models
import django.db.models.deletion
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_alter_profile_preferred_sites'),
        ('observations', '0157_alter_specieimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='volontari_free',
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
        migrations.CreateModel(
            name='SiteVolunteers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profilo volontario')),
                ('sites', models.ManyToManyField(to='observations.site', verbose_name='Siti')),
            ],
            options={
                'verbose_name': 'Siti preferiti dai volontari',
                'verbose_name_plural': 'Siti di salvataggio per i volontari',
                'ordering': ['profile'],
                'managed': True,
            },
        ),
    ]
