# Generated by Django 4.1 on 2023-02-25 15:24

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_delete_preferredsitesnumber'),
        ('observations', '0159_alter_specieimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='volontari',
            field=models.ManyToManyField(blank=True, help_text='Iniziare a digitare un nome, quindi ->>>CLICCARE<<<- sul nome che si desidera aggiungere', null=True, to='profiles.profile', verbose_name='Volontari registrati (CON PROFILO SU SAVE THE PRINCE)'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
