# Generated by Django 4.1 on 2024-05-14 14:50

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0164_alter_specieimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyreport',
            name='specie_toexclude',
            field=models.ManyToManyField(blank=True, null=True, related_name='specie_toexclude', to='observations.specie', verbose_name='Specie da escludere dai report'),
        ),
    ]
