# Generated by Django 4.1 on 2025-02-17 15:52

from django.db import migrations, models
import django.db.models.deletion
import observations.models
import sorl.thumbnail.fields
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0165_delete_siteview_site_lunghezza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(help_text='Immagine del giornale', upload_to='journals/%Y-%m-%d/', verbose_name='Immagine')),
                ('descr', utils.models.ShortTextField(blank=True, null=True, verbose_name='Descrizione eventuale')),
                ('author', models.CharField(blank=True, max_length=300, null=True, verbose_name='Autorice/autore')),
            ],
            options={
                'verbose_name': 'Immagine di una specie particolare nella sessione',
                'verbose_name_plural': 'Immagini di una specie particolare nella sessione',
            },
        ),
        migrations.DeleteModel(
            name='SiteView',
        ),
        migrations.AlterModelOptions(
            name='yearlyreport',
            options={'ordering': ['-year', 'site'], 'verbose_name': 'Report annuale', 'verbose_name_plural': 'Report annuali'},
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='malati',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero esemplari sospetti malati'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='malati_analisi',
            field=models.BooleanField(blank=True, null=True, verbose_name="Inviati campioni per l'analisi?"),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='malati_conferma',
            field=models.BooleanField(blank=True, null=True, verbose_name='Malattia confermata?'),
        ),
        migrations.AddField(
            model_name='observationdetail',
            name='malati_descrizione',
            field=utils.models.ShortTextField(blank=True, null=True, verbose_name='Descrizione esemplari'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
        migrations.AddField(
            model_name='observationdetailimage',
            name='observationdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observationdetailimages', to='observations.observationdetail', verbose_name='Specie in una sessione'),
        ),
    ]
