# Generated by Django 4.1 on 2025-02-17 15:55

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0167_site_lunghezza_alter_specieimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdetail',
            name='malati_analisi_invio',
            field=models.BooleanField(blank=True, null=True, verbose_name="Inviati campioni per l'analisi?"),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='malati_analisi',
            field=models.BooleanField(blank=True, null=True, verbose_name="Raccolti campioni per l'analisi?"),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
