# Generated by Django 4.1 on 2025-02-17 16:01

from django.db import migrations, models
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0168_observationdetail_malati_analisi_invio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdetail',
            name='malati_descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione esemplari'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
    ]
