# Generated by Django 4.1 on 2025-02-24 05:59

from django.db import migrations, models
import django.db.models.deletion
import observations.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0169_alter_observationdetail_malati_descrizione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationdetail',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail_session', to='observations.session', verbose_name='Uscita di salvataggio'),
        ),
        migrations.AlterField(
            model_name='observationdetail',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observationdetail_specie', to='observations.specie', verbose_name='Specie'),
        ),
        migrations.AlterField(
            model_name='sessionimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionimages', to='observations.session', verbose_name='Uscita di salvataggio'),
        ),
        migrations.AlterField(
            model_name='sitedoc',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitedocs', to='observations.site', verbose_name='Sito di salvataggio'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteimages', to='observations.site', verbose_name='Sito di salvataggio'),
        ),
        migrations.AlterField(
            model_name='speciedoc',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciedocs', to='observations.specie', verbose_name='Specie'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Immagini rappresentative della specie', null=True, upload_to=observations.models.specieimage_upload_function, verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='specieimage',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specieimages', to='observations.specie', verbose_name='Specie'),
        ),
        migrations.AlterField(
            model_name='yearlyreportimage',
            name='yearly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlyreportimages', to='observations.yearlyreport', verbose_name='Immagini report annuale'),
        ),
    ]
