# Generated by Django 2.1.2 on 2018-10-29 08:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0015_auto_20181028_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Data di pubblicazione')),
                ('title', tinymce.models.HTMLField(default='Una notizia!', verbose_name='Titolo')),
                ('new', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Corpo')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Association')),
            ],
        ),
    ]
