# Generated by Django 2.1.2 on 2018-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181029_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
