# Generated by Django 2.1.2 on 2018-11-01 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0030_auto_20181101_1955'),
        ('profiles', '0016_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_auto_20181029_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Post',
        ),
    ]
