# Generated by Django 2.1.2 on 2018-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181101_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='Una notizia!', max_length=200, null=True, verbose_name='Titolo'),
        ),
    ]
