# Generated by Django 2.1.3 on 2018-11-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20181101_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Association', verbose_name='Associazione di riferimento'),
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Site', verbose_name='Sito di salvataggio'),
        ),
    ]
