# Generated by Django 2.1.3 on 2018-12-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20181128_1706'),
        ('news', '0006_auto_20181128_1634'),
    ]

    operations = [
    ]
