# Generated by Django 2.1.4 on 2018-12-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20181210_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
