# Generated by Django 2.1.2 on 2019-03-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190308_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author_id',
        ),
    ]
