# Generated by Django 2.2 on 2022-03-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210209_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date'], 'verbose_name': 'Novità', 'verbose_name_plural': 'Novità'},
        ),
    ]
