# Generated by Django 4.1 on 2022-08-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20220316_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'Novità', 'verbose_name_plural': 'Novità'},
        ),
    ]
