# Generated by Django 2.1.2 on 2018-10-23 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='Associazione')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='logo/%Y-%m-%d/', verbose_name='Logo')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Regione')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='WWW')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='FB')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='FB')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='association_verified',
            field=models.BooleanField(default=False, verbose_name='Associazione verificata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verificata'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Immagine di profilo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='association',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Association'),
        ),
    ]
