# Generated by Django 2.1.2 on 2018-10-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181023_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='email',
        ),
        migrations.AlterField(
            model_name='association',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='FB'),
        ),
        migrations.AlterField(
            model_name='association',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='WWW'),
        ),
    ]
