# Generated by Django 2.1.2 on 2018-10-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181025_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='picture',
            new_name='image',
        ),
    ]
