# Generated by Django 2.1.2 on 2018-10-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20181027_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': 'Associazione', 'verbose_name_plural': 'Associazioni'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profilo utente', 'verbose_name_plural': 'Profili utente'},
        ),
    ]
