# Generated by Django 2.1.2 on 2018-10-27 20:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181027_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, max_length=200, null=True, verbose_name='Short Bio'),
        ),
    ]
