# Generated by Django 2.1.2 on 2018-10-27 21:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181027_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='Short Bio'),
        ),
    ]
