# Generated by Django 2.1.2 on 2018-10-28 11:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181027_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='logo/%Y-%m-%d/', verbose_name='Logo'),
        ),
    ]
