# Generated by Django 2.1.2 on 2018-10-28 11:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20181028_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='bio',
        ),
        migrations.AddField(
            model_name='association',
            name='descrizione',
            field=tinymce.models.HTMLField(blank=True, help_text="Una breve descrizione della storia e scopi dell'Associazione", max_length=1000, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='association_verified',
            field=models.BooleanField(default=False, verbose_name='Associazione verificata?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verificata?'),
        ),
    ]
