# Generated by Django 2.1.2 on 2018-10-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20181028_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ruolo'),
        ),
    ]
