# Generated by Django 2.1.2 on 2018-12-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20181227_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, choices=[('Agrigento', 'Agrigento'), ('Alessandria', 'Alessandria'), ('Ancona', 'Ancona'), ('Aosta', 'Aosta'), ('Arezzo', 'Arezzo'), ('Ascoli Piceno', 'Ascoli Piceno'), ('Asti', 'Asti'), ('Avellino', 'Avellino'), ('Barletta - Andria - Trani', 'Barletta - Andria - Trani'), ('Belluno', 'Belluno'), ('Benevento', 'Benevento'), ('Bergamo', 'Bergamo'), ('Biella', 'Biella'), ('Bolzano', 'Bolzano'), ('Brescia', 'Brescia'), ('Brindisi', 'Brindisi'), ('Caltanissetta', 'Caltanissetta'), ('Campobasso', 'Campobasso'), ('Caserta', 'Caserta'), ('Catanzaro', 'Catanzaro'), ('Chieti', 'Chieti'), ('Como', 'Como'), ('Cosenza', 'Cosenza'), ('Cremona', 'Cremona'), ('Crotone', 'Crotone'), ('Cuneo', 'Cuneo'), ('Enna', 'Enna'), ('Fermo', 'Fermo'), ('Ferrara', 'Ferrara'), ('Foggia', 'Foggia'), ('Forlì - Cesena', 'Forlì - Cesena'), ('Frosinone', 'Frosinone'), ('Grosseto', 'Grosseto'), ('Imperia', 'Imperia'), ('Isernia', 'Isernia'), ('La Spezia', 'La Spezia'), ('LAquila', 'LAquila'), ('Latina', 'Latina'), ('Lecce', 'Lecce'), ('Lecco', 'Lecco'), ('Livorno', 'Livorno'), ('Lodi', 'Lodi'), ('Lucca', 'Lucca'), ('Macerata', 'Macerata'), ('Mantova', 'Mantova'), ('Massa - Carrara', 'Massa - Carrara'), ('Matera', 'Matera'), ('Modena', 'Modena'), ('Monza e Brianza', 'Monza e Brianza'), ('Novara', 'Novara'), ('Nuoro', 'Nuoro'), ('Oristano', 'Oristano'), ('Padova', 'Padova'), ('Parma', 'Parma'), ('Pavia', 'Pavia'), ('Perugia', 'Perugia'), ('Pesaro e Urbino', 'Pesaro e Urbino'), ('Pescara', 'Pescara'), ('Piacenza', 'Piacenza'), ('Pisa', 'Pisa'), ('Pistoia', 'Pistoia'), ('Potenza', 'Potenza'), ('Prato', 'Prato'), ('Ragusa', 'Ragusa'), ('Ravenna', 'Ravenna'), ('Reggio Emilia', 'Reggio Emilia'), ('Rieti', 'Rieti'), ('Rimini', 'Rimini'), ('Rovigo', 'Rovigo'), ('Salerno', 'Salerno'), ('Sassari', 'Sassari'), ('Savona', 'Savona'), ('Siena', 'Siena'), ('Siracusa', 'Siracusa'), ('Sondrio', 'Sondrio'), ('Sud Sardegna', 'Sud Sardegna'), ('Taranto', 'Taranto'), ('Teramo', 'Teramo'), ('Terni', 'Terni'), ('Trapani', 'Trapani'), ('Trento', 'Trento'), ('Treviso', 'Treviso'), ('Varese', 'Varese'), ('Verbano - Cusio - Ossola', 'Verbano - Cusio - Ossola'), ('Vercelli', 'Vercelli'), ('Verona', 'Verona'), ('Vibo Valentia', 'Vibo Valentia'), ('Vicenza', 'Vicenza'), ('Viterbo', 'Viterbo')], max_length=40, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province_verified',
            field=models.BooleanField(default=False, verbose_name='Provincia verificata?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Association', verbose_name='Associazione'),
        ),
    ]
