# Generated by Django 2.1.2 on 2019-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20181227_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liberatoria',
            field=models.FileField(blank=True, null=True, upload_to='liberatorie/%Y-%m-%d/', verbose_name='Liberatoria'),
        ),
    ]
