# Generated by Django 2.1.2 on 2019-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_liberatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liberatoria',
            field=models.ImageField(blank=True, null=True, upload_to='liberatorie/%Y-%m-%d/', verbose_name='Liberatoria'),
        ),
    ]
