# Generated by Django 2.1.2 on 2019-02-20 16:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190220_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liberatoria',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='liberatorie/%Y-%m-%d/', verbose_name='Liberatoria'),
        ),
    ]
