# Generated by Django 2.1.2 on 2019-02-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20190220_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liberatoria',
            field=models.FileField(blank=True, null=True, upload_to='liberatorie/%Y-%m-%d/', verbose_name='Liberatoria'),
        ),
    ]
