# Generated by Django 2.1.2 on 2019-02-22 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0051_sitesummary'),
        ('profiles', '0027_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredSitesNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Siti preferiti dalla/dal volontaria/o',
                'verbose_name_plural': 'Siti preferiti dalle/dai volontarie/o',
            },
        ),
    ]
