# Generated by Django 2.1.2 on 2020-02-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0059_auto_20200212_2230'),
        ('profiles', '0028_preferredsitesnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Site', verbose_name='Indica il tuo sito di salvataggio preferito'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_show',
            field=models.BooleanField(default=True, verbose_name='Vuoi che il tuo profilo appaia nelle liste di volontari per i siti?'),
        ),
    ]
