# Generated by Django 2.1.2 on 2020-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20200213_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='modello_liberatoria',
            field=models.FileField(blank=True, null=True, upload_to='liberatorie/MODELLI/', verbose_name='Liberatoria'),
        ),
    ]
