# Generated by Django 2.1.2 on 2020-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_association_modello_liberatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='modello_liberatoria',
            field=models.FileField(blank=True, null=True, upload_to='liberatorie/MODELLI/', verbose_name='Modello di liberatoria'),
        ),
    ]
