# Generated by Django 2.1.2 on 2020-02-13 12:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20200213_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='descrizione',
            field=tinymce.models.HTMLField(blank=True, help_text="Una breve descrizione della storia e scopi dell'Associazione", max_length=10000, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='association',
            name='modello_liberatoria',
            field=models.FileField(null=True, upload_to='liberatorie/MODELLI/', verbose_name='Modello di liberatoria'),
        ),
    ]
