# Generated by Django 2.1.2 on 2020-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0060_auto_20200213_1313'),
        ('profiles', '0032_auto_20200213_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.ManyToManyField(blank=True, null=True, to='observations.Session', verbose_name='Sessioni alle quali il volontario ha partecipato'),
        ),
    ]
