# Generated by Django 2.1.2 on 2020-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_profile_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sessions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='observations.Session', verbose_name='Sessioni alle quali il volontario ha partecipato'),
        ),
    ]
