# Generated by Django 2.1.2 on 2020-02-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_remove_profile_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volontaria/o'), ('reference-site', 'Referente sito'), ('reference-organization', 'Referente Associazione'), ('admin', 'Amministratore generale')], default='Volontaria/o', max_length=400, verbose_name='Ruolo'),
        ),
    ]
