# Generated by Django 2.1.2 on 2020-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20200213_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_descr',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ruolo esteso'),
        ),
    ]
