# Generated by Django 2.2 on 2021-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_profile_role_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='modello_liberatoria',
            field=models.FileField(blank=True, null=True, upload_to='liberatorie/MODELLI/', verbose_name='Modello di liberatoria'),
        ),
    ]
