# Generated by Django 2.2 on 2021-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20210207_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='aaa', max_length=400, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='aaa', max_length=400, verbose_name='Cognome'),
        ),
    ]
