# Generated by Django 2.2 on 2021-02-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20210208_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='profile_surname',
        ),
    ]
