# Generated by Django 2.2 on 2021-02-09 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20210208_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_show',
            field=models.BooleanField(default=False, verbose_name='Vuoi che il tuo profilo appaia nelle liste di volontari per i siti?'),
        ),
    ]
