# Generated by Django 2.2 on 2021-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20210209_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
