# Generated by Django 2.2 on 2021-02-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20210209_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_show',
            field=models.BooleanField(default=False, verbose_name='Vuoi che la tua mail sia visibile agli altri volontari?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_show',
            field=models.BooleanField(default=False, verbose_name='Vuoi che il tuo numero di telefono sia visibile agli altri volontari?'),
        ),
    ]
