# Generated by Django 2.2 on 2021-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20210228_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volontaria/o'), ('reference-site', 'Referente sito'), ('reference-organization', 'Referente Associazione'), ('admin', 'Amministratore generale')], default='volunteer', max_length=400, verbose_name='Ruolo'),
        ),
    ]
