# Generated by Django 2.2 on 2022-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20210316_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='mail',
            field=models.EmailField(default='salvataggioanfibi@gmail.com', max_length=1024, verbose_name='Mail'),
        ),
    ]
