# Generated by Django 2.2 on 2022-01-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_association_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='mail',
            new_name='email',
        ),
    ]
