# Generated by Django 2.2 on 2022-03-22 17:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0143_auto_20220322_1838'),
        ('profiles', '0047_auto_20220316_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(default='aaa', max_length=400, verbose_name='Nome')),
                ('profile_surname', models.CharField(default='aaa', max_length=400, verbose_name='Cognome')),
                ('role', models.CharField(choices=[('volunteer', 'Volontaria/o'), ('reference-site', 'Referente sito'), ('reference-organization', 'Referente Associazione'), ('admin', 'Amministratore generale')], default='volunteer', max_length=400, verbose_name='Ruolo')),
                ('role_descr', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ruolo esteso')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=True, verbose_name='Email verificata?')),
                ('association_verified', models.BooleanField(default=True, verbose_name='Associazione verificata?')),
                ('province', models.CharField(blank=True, choices=[('Agrigento', 'Agrigento'), ('Alessandria', 'Alessandria'), ('Ancona', 'Ancona'), ('Aosta', 'Aosta'), ('Arezzo', 'Arezzo'), ('Ascoli Piceno', 'Ascoli Piceno'), ('Asti', 'Asti'), ('Avellino', 'Avellino'), ('Città Metropolitana di Bari', 'Città Metropolitana di Bari'), ('Barletta - Andria - Trani', 'Barletta - Andria - Trani'), ('Belluno', 'Belluno'), ('Benevento', 'Benevento'), ('Bergamo', 'Bergamo'), ('Città Metropolitana di Bologna', 'Città Metropolitana di Bologna'), ('Biella', 'Biella'), ('Bolzano', 'Bolzano'), ('Brescia', 'Brescia'), ('Brindisi', 'Brindisi'), ('Caltanissetta', 'Caltanissetta'), ('Città Metropolitana di Cagliari', 'Città Metropolitana di Cagliari'), ('Campobasso', 'Campobasso'), ('Caserta', 'Caserta'), ('Città Metropolitana di Catania', 'Città Metropolitana di Catania'), ('Catanzaro', 'Catanzaro'), ('Chieti', 'Chieti'), ('Como', 'Como'), ('Cosenza', 'Cosenza'), ('Cremona', 'Cremona'), ('Crotone', 'Crotone'), ('Cuneo', 'Cuneo'), ('Enna', 'Enna'), ('Fermo', 'Fermo'), ('Ferrara', 'Ferrara'), ('Città Metropolitana di Firenze', 'Città Metropolitana di Firenze'), ('Foggia', 'Foggia'), ('Forlì - Cesena', 'Forlì - Cesena'), ('Frosinone', 'Frosinone'), ('Città Metropolitana di Genova', 'Città Metropolitana di Genova'), ('Grosseto', 'Grosseto'), ('Imperia', 'Imperia'), ('Isernia', 'Isernia'), ('La Spezia', 'La Spezia'), ('LAquila', 'LAquila'), ('Latina', 'Latina'), ('Lecce', 'Lecce'), ('Lecco', 'Lecco'), ('Livorno', 'Livorno'), ('Lodi', 'Lodi'), ('Lucca', 'Lucca'), ('Macerata', 'Macerata'), ('Mantova', 'Mantova'), ('Massa - Carrara', 'Massa - Carrara'), ('Matera', 'Matera'), ('Città Metropolitana di Messina', 'Città Metropolitana di Messina'), ('Città Metropolitana di Milano', 'Città Metropolitana di Milano'), ('Modena', 'Modena'), ('Monza e Brianza', 'Monza e Brianza'), ('Novara', 'Novara'), ('Città Metropolitana di Napoli', 'Città Metropolitana di Napoli'), ('Nuoro', 'Nuoro'), ('Oristano', 'Oristano'), ('Padova', 'Padova'), ('Città Metropolitana di Palermo', 'Città Metropolitana di Palermo'), ('Parma', 'Parma'), ('Pavia', 'Pavia'), ('Perugia', 'Perugia'), ('Pesaro e Urbino', 'Pesaro e Urbino'), ('Pescara', 'Pescara'), ('Piacenza', 'Piacenza'), ('Pisa', 'Pisa'), ('Pistoia', 'Pistoia'), ('Potenza', 'Potenza'), ('Prato', 'Prato'), ('Ragusa', 'Ragusa'), ('Ravenna', 'Ravenna'), ('Città Metropolitana di Reggio Calabria', 'Città Metropolitana di Reggio Calabria'), ('Reggio Emilia', 'Reggio Emilia'), ('Rieti', 'Rieti'), ('Rimini', 'Rimini'), ('Città Metropolitana di Roma Capitale', 'Città Metropolitana di Roma Capitale'), ('Rovigo', 'Rovigo'), ('Salerno', 'Salerno'), ('Sassari', 'Sassari'), ('Savona', 'Savona'), ('Siena', 'Siena'), ('Siracusa', 'Siracusa'), ('Sondrio', 'Sondrio'), ('Sud Sardegna', 'Sud Sardegna'), ('Taranto', 'Taranto'), ('Teramo', 'Teramo'), ('Terni', 'Terni'), ('Città Metropolitana di Torino', 'Città Metropolitana di Torino'), ('Trapani', 'Trapani'), ('Trento', 'Trento'), ('Treviso', 'Treviso'), ('Varese', 'Varese'), ('Città Metropolitana di Venezia', 'Città Metropolitana di Venezia'), ('Verbano - Cusio - Ossola', 'Verbano - Cusio - Ossola'), ('Vercelli', 'Vercelli'), ('Verona', 'Verona'), ('Vibo Valentia', 'Vibo Valentia'), ('Vicenza', 'Vicenza'), ('Viterbo', 'Viterbo')], max_length=40, null=True, verbose_name='Provincia o Città Metropolitana')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefono')),
                ('province_verified', models.BooleanField(default=True, verbose_name='Provincia verificata?')),
                ('profile_show', models.BooleanField(default=False, verbose_name='Vuoi che il tuo profilo appaia nelle liste di volontari per i siti?')),
                ('phone_show', models.BooleanField(default=False, verbose_name='Vuoi che il tuo numero di telefono sia visibile agli altri volontari?')),
                ('mail_show', models.BooleanField(default=False, verbose_name='Vuoi che la tua mail sia visibile agli altri volontari?')),
                ('liberatoria', models.FileField(upload_to='liberatorie/%Y-%m-%d/', verbose_name='Liberatoria')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Association', verbose_name='Associazione')),
                ('preferred_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Site', verbose_name='Indica il tuo sito di salvataggio preferito')),
            ],
            options={
                'verbose_name': 'Dati di un* volontari* non registrat*',
                'verbose_name_plural': 'Dati dei/delle volontari* non registrat*',
            },
        ),
    ]
