# Generated by Django 2.2 on 2022-03-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_freeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeprofile',
            name='mail_show',
            field=models.BooleanField(default=False, verbose_name='Vuoi che la mail sia visibile agli altri volontari?'),
        ),
        migrations.AlterField(
            model_name='freeprofile',
            name='phone_show',
            field=models.BooleanField(default=False, verbose_name='Vuoi che il numero di telefono sia visibile agli altri volontari?'),
        ),
        migrations.AlterField(
            model_name='freeprofile',
            name='preferred_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Site', verbose_name='Sito di salvataggio preferito'),
        ),
        migrations.AlterField(
            model_name='freeprofile',
            name='profile_show',
            field=models.BooleanField(default=False, verbose_name='Vuoi che il profilo appaia nelle liste di volontari per i siti?'),
        ),
    ]
