# Generated by Django 2.2 on 2022-03-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_auto_20220322_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeprofile',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Association', verbose_name='Associazione'),
        ),
    ]
