# Generated by Django 2.2 on 2022-04-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0149_auto_20220421_0814'),
        ('profiles', '0050_auto_20220322_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_sites',
            field=models.ManyToManyField(null=True, related_name='profile_preferred_sites', to='observations.Site', verbose_name='Indica i tuoi siti di salvataggio preferiti'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_preferred_site', to='observations.Site', verbose_name='Indica il tuo sito di salvataggio preferito'),
        ),
    ]
