# Generated by Django 4.1 on 2023-02-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0157_alter_specieimage_image'),
        ('profiles', '0052_profile_update_mail_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_sites',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_preferred_sites', to='observations.site', verbose_name='Indica i tuoi siti di salvataggio preferiti'),
        ),
    ]
