# Generated by Django 4.1 on 2023-02-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_alter_profile_preferred_sites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreferredSitesNumber',
        ),
    ]
