# Generated by Django 4.1 on 2023-03-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0163_alter_specieimage_image'),
        ('profiles', '0055_association_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'managed': True, 'verbose_name': 'Associazione', 'verbose_name_plural': 'Associazioni'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_sites',
        ),
        migrations.AlterField(
            model_name='freeprofile',
            name='preferred_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.site', verbose_name='Sito di salvataggio preferito'),
        ),
    ]
