# Generated by Django 4.1 on 2023-03-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_alter_association_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeprofile',
            name='profile_name',
            field=models.CharField(max_length=400, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='freeprofile',
            name='profile_surname',
            field=models.CharField(max_length=400, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=400, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_surname',
            field=models.CharField(max_length=400, verbose_name='Cognome'),
        ),
    ]
