# Generated by Django 4.1 on 2024-05-14 14:50

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_alter_freeprofile_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liberatoria',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.liberatoria_upload, verbose_name='Liberatoria'),
        ),
    ]
