# Generated by Django 2.2 on 2021-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Domanda')),
                ('answer', models.TextField(verbose_name='Risposta')),
            ],
            options={
                'verbose_name': 'Domanda con risposta',
                'verbose_name_plural': 'Domande e risposte',
            },
        ),
    ]
