# Generated by Django 2.2 on 2021-02-28 15:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='Risposta'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=tinymce.models.HTMLField(verbose_name='Domanda'),
        ),
    ]
