# Generated by Django 2.2 on 2021-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20210228_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='faqtype',
            field=models.CharField(choices=[('generali', 'FAQ generali'), ('volontari', 'FAQ per i volontari'), ('referenti', 'FAW per i referenti')], default='volontari', max_length=128, verbose_name='Categoria'),
        ),
    ]
