# Generated by Django 2.2 on 2021-02-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_faqmodel_faqtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='faqtype',
            field=models.CharField(choices=[('generali', 'FAQ generali'), ('volontari', 'FAQ per i volontari'), ('referenti', 'FAQ per i referenti')], default='volontari', max_length=128, verbose_name='Categoria'),
        ),
    ]
