# Generated by Django 2.2 on 2021-05-11 05:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20210228_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuni',
            fields=[
                ('comuni_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reg', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice regione')),
                ('cod_prov', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice provincia')),
                ('comune', models.CharField(max_length=512, verbose_name='Nome')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3035, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'db_table': 'env_data"."comuni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reg', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice regione')),
                ('cod_prov', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice provincia')),
                ('provincia', models.CharField(max_length=512, verbose_name='Nome')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3035, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'db_table': 'env_data"."province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regioni',
            fields=[
                ('regioni_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reg', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice')),
                ('regione', models.CharField(max_length=512, verbose_name='Nome')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3035, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'db_table': 'env_data"."regioni',
                'managed': False,
            },
        ),
    ]
