# Generated by Django 2.2 on 2022-02-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_comuni_province_regioni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuni',
            options={'managed': False, 'ordering': ['comune'], 'verbose_name': 'Comune', 'verbose_name_plural': 'Comuni'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'managed': False, 'ordering': ['provincia'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Province'},
        ),
        migrations.AlterModelOptions(
            name='regioni',
            options={'managed': False, 'ordering': ['regione'], 'verbose_name': 'Regione', 'verbose_name_plural': 'Regioni'},
        ),
    ]
