# Generated by Django 2.2 on 2022-02-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20220219_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comuni',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Regioni',
        ),
    ]
