# Generated by Django 2.2 on 2022-02-19 10:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20220219_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuni',
            fields=[
                ('comune', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Comune')),
                ('comuni_id', models.IntegerField(db_column='id', verbose_name='ID')),
                ('cod_reg', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice regione')),
                ('cod_prov', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice provincia')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3035, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'db_table': 'env_data"."comuni',
                'ordering': ['comune'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provincia', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Nome')),
                ('province_id', models.IntegerField(db_column='id', verbose_name='ID')),
                ('cod_reg', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice regione')),
                ('cod_prov', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice provincia')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3035, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'db_table': 'env_data"."province',
                'ordering': ['provincia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regioni',
            fields=[
                ('regione', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Nome')),
                ('regioni_id', models.IntegerField(db_column='id', verbose_name='ID')),
                ('cod_reg', models.CharField(blank=True, max_length=512, null=True, verbose_name='Codice')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3035, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'db_table': 'env_data"."regioni',
                'ordering': ['regione'],
                'managed': False,
            },
        ),
    ]
